test_rle_memory: fix `test_rle_memory_receiver_new` test
Fix `test_rle_memory_receiver_new` test:
```console
[ RUN      ] test_rle_memory_receiver_new
[  ERROR   ] --- receiver == NULL
[   LINE   ] --- librle/tests/test_rle_memory.c:141: error: Failure!
[  FAILED  ] test_rle_memory_receiver_new
```

The structure `rle_receiver` contains `RLE_MAX_FRAG_NUMBER` contexts.  Thus, to
simulate memory allocation errors we need fewer than `RLE_MAX_FRAG_NUMBER`
allocations, as we do in the `test_rle_memory_transmitter_new` test.