test_rle_common.h: fix linker error caused by multiple definition of `payload_initializer`
Modern compilers (GCC 10+) enable `-fno-common` by default, which treats
uninitialized global variables in headers as multiple definitions during
linking.

Add `extern` keyword to `payload_initializer` declaration in
`tests/include/test_rle_common.h`.

Fixes the following linker error:
```console
test_rle_common.h:59: multiple definition of `payload_initializer';
```